version: '3.8'

services:
  client:
    build:
      context: ./ecommerceclient
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - maxNetwork

  server:
    build:
      context: ./max-core-tech-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - maxNetwork
    
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=maxcoretechserver
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  maxNetwork:
    driver: bridge